---
spring.config.activate.on-profile: sandbox, test

spring:
  flyway:
    enabled: true
    baseline-on-migrate: true

---
spring.config.activate.on-profile: stable

spring:
  flyway:
    enabled: false
