const val USER_ENTITY_LOCK_KEY = "USER-ENTITY-LOCK"
const val REVIEW_LIKE_LOCK_KEY = "REVIEW-LIKE-LOCK"
const val POPULAR_SEARCH_KEY = "POPULAR-SEARCH-KEY"
const val POPULAR_SEARCH_TOPIC = "popular-search-cache-update"
const val POPULAR_SEARCH_SCHEDULER_LOCK = "updatePopularSearchesCacheLock"
