ALTER TABLE REWARDS
DROP COLUMN reward_type;

ALTER TABLE REWARDS
DROP COLUMN reward_reason;

ALTER TABLE REWARDS
    ADD coin_received NUMBER(1) NOT NULL;

ALTER TABLE REWARDS
    ADD reward_type VARCHAR2(20) NOT NULL;
