name: Release Tag
on:
  push:
    branches:
      - stable
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 배포일자 추출
        run: echo "##[set-output name=release_date;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{8}\-[0-9]{1,3}')"
        id: extract_release_date
      - name: Release 생성
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_release_date.outputs.release_date }}
          release_name: ${{ steps.extract_release_date.outputs.release_date }}
